backend:
  name: "github"
  repo: "omiron33/gatsbyPro"

media_folder: static/img
public_folder: /img

collections:
  - name: "product"
    label: "Product"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product", name: "product", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
